data:
  input_size:
  - 426
  - 560
  num_workers: 2
  pin_memory: true
data_dir: /cluster/courses/cil/monocular_depth/data
device: cuda
logging:
  entity: MonocularDepthEstimation
  log: true
  log_every_k_epochs: 1
  log_every_k_steps: -1
  log_images: true
  project_name: MonocularDepthEstimation
  run_name: Random Search 5
  upload_to_wandb: true
  val_every_step_log: true
model:
  conv_transpose: true
  dilation: 4
  hidden_channels: 16
  include_pretrained_head: false
  num_heads: 1
  type: dinov2_backboned_unet
  weight_initialization: glorot
output_dir: ./output
seed: 0
train:
  batch_size: 8
  gradient_loss_weight: 4
  gradient_regularizer_weight: 0
  head_penalty_weight:
  - 2
  - 0
  learning_rate: 0.0001
  num_epochs: 15
  weight_decay: 0.001
