device: "cuda" # or "cpu"
seed: 0

data_dir: "TODO: SET PATH"
output_dir: "TODO: SET PATH"

run_name: ""

train:
  num_epochs: 1
  batch_size: 4
  learning_rate: 0.0001
  weight_decay: 0.0001

data:
  input_size: [426, 560]
  num_workers: 4
  pin_memory: true
