device: "cuda" # or "cpu"
seed: 0

data_dir: "/cluster/courses/cil/monocular_depth/data"
output_dir: "./output" # "/work/scratch/smarian/output"  # Replace with your username if you want to save the output to scratch to avoid quota issues

train:
  num_epochs: 5
  batch_size: 8
  learning_rate: 0.01
  weight_decay: 0.01
  gradient_regularizer_weight: 0

model:
  hidden_channels: 32
  dilation: 1

data:
  input_size: [426, 560] # Size of the input images (height, width). There should be no need to change this
  num_workers: 2         # How many workers to use for parallel data loading
  pin_memory: true

logging:
  log: true                       # Whether to log the training or not (Useful for debugging to not create a new run every time)
  log_images: true                # Whether to log a comparison figure between predictions and ground truth (at both epoch- and step-level)
  val_every_step_log: true        # Whether to run on validation set at every step-level log
  log_every_k_epochs: 1           # How frequent to perform epoch-level logging (set to -1 to disable)
  log_every_k_steps: -1           # How frequent to perform step-level logging (set to -1 to disable)
  run_name: ""
  entity: "MonocularDepthEstimation"       # Which entity/team to log to. There should be no need to change this
  project_name: "MonocularDepthEstimation" # Which project to log to. There should be no need to change this
  upload_to_wandb: true                    # Whether to upload the model and predicted depth maps to wandb