data:
  input_size:
  - 426
  - 560
  num_workers: 2
  pin_memory: true
data_dir: /cluster/courses/cil/monocular_depth/data
device: cuda
logging:
  entity: MonocularDepthEstimation
  log: true
  log_every_k_epochs: 1
  log_every_k_steps: -1
  log_images: true
  project_name: MonocularDepthEstimation
  run_name: bilateral_filter_test
  upload_to_wandb: true
  val_every_step_log: true
model:
  conv_transpose: true
  dilation: 1
  hidden_channels: 32
  include_pretrained_head: true
  num_heads: 16
  type: depth_anything
  wandb_artifact_fullname: MonocularDepthEstimation/MonocularDepthEstimation/best_model:v5
  weight_initialization: default
output_dir: ./output
post_process:
  bilateral_filter:
    d: 10
    sigma_color: 255
    sigma_space: 255
seed: 0
train:
  batch_size: 8
