data:
  input_size:
  - 426
  - 560
  num_workers: 2
  pin_memory: true
data_dir: /cluster/courses/cil/monocular_depth/data
device: cuda
logging:
  entity: MonocularDepthEstimation
  log: true
  log_every_k_epochs: 1
  log_every_k_steps: -1
  log_images: true
  project_name: MonocularDepthEstimation
  run_name: FineTune/diunet/id_1_guided_filter_normalized_std_interpolation
  upload_to_wandb: true
  val_every_step_log: true
model:
  conv_transpose: true
  dilation: 1
  hidden_channels: 32
  include_pretrained_head: false
  num_heads: 4
  type: diunet
  wandb_artifact_fullname: MonocularDepthEstimation/MonocularDepthEstimation/best_model:v38
  weight_initialization: glorot
output_dir: ./output
post_process:
  guided_filter:
    eps: 0.001
    r: 16
  normalized_std_interpolation: {}
seed: 0
train:
  batch_size: 8
